### PR TITLE
Add Bangla abbreviation list

### PR DESCRIPTION
**Pull request by Nishat18**
Hi @lonvia,

Can you please review this pull request? I'm hoping to contribute more to this project.

### CODE REVIEW

**Comment by mtmail** [comment]
The last 3 entries I can understand, they're part of many addresses (street names). But what does "Value Added Tax" have to do with place name search?

If an organization like https://www.openstreetmap.org/search?query=%E0%A6%9F%E0%A7%87%E0%A6%B2%E0%A6%BF%E0%A6%AB%E0%A7%8B%E0%A6%A8%20%E0%A6%B6%E0%A6%BF%E0%A6%B2%E0%A7%8D%E0%A6%AA%20%E0%A6%B8%E0%A6%82%E0%A6%B8%E0%A7%8D%E0%A6%A5%E0%A6%BE#map=18/23.89188/90.40325 has an abbreviation it can be added to the place as `short_name` https://wiki.openstreetmap.org/wiki/Names
instead.

Have a look at Ukrainian or Tamil. The entries should be only those used often in addresses
https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations#%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AF%8D_-_Tamil

**Comment by Nishat18** [comment]
> The last 3 entries I can understand, they're part of many addresses (street names). But what does "Value Added Tax" have to do with place name search?
> 
> If an organization like https://www.openstreetmap.org/search?query=%E0%A6%9F%E0%A7%87%E0%A6%B2%E0%A6%BF%E0%A6%AB%E0%A7%8B%E0%A6%A8%20%E0%A6%B6%E0%A6%BF%E0%A6%B2%E0%A7%8D%E0%A6%AA%20%E0%A6%B8%E0%A6%82%E0%A6%B8%E0%A7%8D%E0%A6%A5%E0%A6%BE#map=18/23.89188/90.40325 has an abbreviation it can be added to the place as `short_name` https://wiki.openstreetmap.org/wiki/Names instead.
> 
> Have a look at Ukrainian or Tamil. The entries should be only those used often in addresses https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations#%E0%AE%A4%E0%AE%AE%E0%AE%BF%E0%AE%B4%E0%AF%8D_-_Tamil

I added that by mistake and I removed it already. Thanks for pointing it out.  I also wanted your guidance about how to add the short name of an organization as I'm new to these things and I am just learning.

**Comment by mtmail** [comment]
@Nishat18

This museum https://www.openstreetmap.org/way/278346578 is a good example.

* name = MoMA
* short_name = MoMA
* alt_name = Museum of Modern Art
* official_name = The Museum of Modern Art

Also this church https://www.openstreetmap.org/relation/9194723

* name = Basílica de la Sagrada Família
* alt_name = Sagrada Família

According to wikipedia https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia one could even add an official_name = "Basílica i Temple Expiatori de la Sagrada Família", too.

Nominatim understands all these names.

Follow-up questions on tagging are better asked on the https://help.openstreetmap.org/ forum.

**Comment by lonvia** [comment]
As @mtmail said, the abbreviations list should only contain abbreviations that are commonly used inside addresses not short names for specific places. The largest part of the list is an abbreviation of the latter type. So I'm closing this.

**Pull request closed without merging**
