### PR TITLE
fix: Ported initial computation of postcode table from PHP to Python

### LINKED ISSUE #2220: Initial computation of postcode table needs porting to Python
The function to [calculate the intial postcode table](https://github.com/osm-search/Nominatim/blob/0d9fe6e49c3cee131d2fd0c2c0ad2e59065621f9/lib-php/setup/SetupClass.php#L70) still needs to be ported from PHP to Python. The postcode calculation needs a general overhaul (see #2049) but it is probably better to first port the PHP function as is before doing any further improvements. The function also needs tests.

Some helpful pointers where to look for code examples:
* porting a admin functions to Python, see for example [port of check_database functions](https://github.com/osm-search/Nominatim/commit/b169e4c88cd99075c7e932aeb6587c97f51e7ed1)
* [tests for ported setup functions](https://github.com/osm-search/Nominatim/blob/master/test/python/test_tools_database_import.py)

### PR DESCRIPTION
**Pull request by Vineet-Sharma29**
fixes #2220 

This PR ports calculatePostcodes function from PHP to Python

PR Status:-
- [x] Porting to Python
- [ ] Testing and code linting

### CODE REVIEW

**Comment by Vineet-Sharma29** [comment]
@lonvia I have ported `calculatePostcodes` function from PHP to Python. Can you please share if there is something needs to changed in the current code? I am not sure of `args` passed in `calculate_postcodes` function in python. Also, for testing what tests one can add for `calculate_postcodes` ?

**Comment by lonvia** [comment]
Please make sure that the code passes all linting checks and tests. Please make sure the code can be executed with the GB and UK postcode files mentioned in the installation instructions.

A test for `calc_postcodes` should check that SQL code in the files that the function loads actually gets executed, that the code can handle absence of the files correctly and that the literal SQL functions you execute do not produce any errors. `test/python/test_tools_database_import.py` has examples for writing such tests.

**Comment by Vineet-Sharma29** [comment]
I have downloaded GB and US postcode files. I am facing some difficulty in setting up database. Can you point out DB setup steps? I couldn't find them in docs

**Comment by mtmail** [comment]
Base installation includes a section on Postgresql setup https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-20/ (similar for CentOS or Ubuntu-18) where a database role gets created. https://nominatim.org/release-docs/develop/develop/Development-Environment/ explains which test programs, e.g. `behave`, `pytest` to install and in which directory to run the test suite locally. The test suite creates a new database and overwrites it on each new test suite run. 

https://github.com/osm-search/Nominatim/blob/master/test/bdd/environment.py shows the setting during a python test suite run. All settings in uppercase, e.g. `DB_HOST` can be overwritten. For example

`behave -DBUILDDIR=/home/myusername/build/ db osm2pgsql`

It's better to start a new discussion https://github.com/osm-search/Nominatim/discussions for setup related questions, otherwise it gets too far off the original issue/PR.

**Comment by lonvia** [comment]
I'm closing this PR as it has gone stale. Please open a new one based on the current code, if you want to continue working on this and have a working version. Or maybe somebody else wants to pick the issue up.

**Pull request closed without merging**
