### PR TITLE
Add script to generate taginfo project description

### PR DESCRIPTION
**Pull request by biswajit-k**
As mentioned in #2938, Nominatim now uses [flex style](https://nominatim.org/release-docs/develop/customize/Import-Styles/) to import places into the database. The flex-style files are present in the [settings](https://github.com/osm-search/Nominatim/tree/master/settings) folder. These files contain the OSM tags which are being used by Nominatim.
The script collects these tags and prints the Taginfo project description in the required [format](https://wiki.openstreetmap.org/wiki/Taginfo/Projects#Project_Files).

It should be noted that `delete` and `extra` tags are not considered in the description because these tags are not part of the search process. These tags are either completely ignored or are just used for displaying extra information with the search results.

### CODE REVIEW

**Comment by biswajit-k** [comment]
Hi @lonvia, request you to please review the PR.

**Comment by lonvia** [comment]
Sorry, I'm really busy at the moment but hope to get to this before the end of the week.

**Comment by lonvia** [comment]
The trick with the shell script is very clever but it can break too easily when the code in flex-base.lua changes. I would be perfectly happy with a solution, where the `MAIN`,  `NAME_KEYS` and `ADDRESS_KEYS` structures are created in the `flex-base.lua` file directly and are made available from the module. The extra code will only have an effect on the setup of the module and that is not performance critical. Once you have that, you can simply execute the original lua script at the beginning of your script and then run your code without additional shell scripting around.

The dkjson library is already packaged in Debian/Ubuntu, so please use the package instead of adding it to the Nominatim source code.

**Comment by lonvia** [comment]
Looks good in general now, I'll have a bit of a closer look later. In the meantime, could you add the taginfo file generation for one of the default styles to the CI tests around [here](https://github.com/osm-search/Nominatim/blob/d69411f414c6e93e558e01e1736f1628fcec67ab/.github/workflows/ci-tests.yml#L257).

**Comment by biswajit-k** [comment]
Hi @lonvia, I have made the required changes. Please have a look.

**Comment by lonvia** [comment]
Thank you, works nicely.

I noticed that the project information is severely out of date. But that has nothing to do with your code, so I'll add a commit on top for that.

**Pull request merged**
