### PR TITLE
Warn about currently used locale

### PR DESCRIPTION
**Pull request by mmaridev**

### CODE REVIEW

**Comment by mmaridev** [comment]
I was here once again since always start from a Proxmox CT image.

Maybe it's time to merge this into the wiki?

/cc @lonvia

**Comment by lonvia** [comment]
I'm not a fan of having commands in these scripts that are purely there for printing something out for the user. The scripts main purpose is to be executed. 

Should we just add `dkpg-reconfigure locale` to the instructions, so it simply works? Could it do damage when locales are already set up? @mtmail what do you think?

**Comment by mtmail** [comment]
I'd add a Troubleshooting FAQ entry for that error message https://nominatim.org/release-docs/latest/admin/Faq/ instead.

**Comment by lonvia** [comment]
Good idea.

**Comment by lonvia** [comment]
Replaced by #3491

**Comment by mmaridev** [comment]
The goal of my PR was to have it published on the
https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-22/
page...

Il Lun 29 Lug 2024, 18:35 Sarah Hoffmann ***@***.***> ha
scritto:

**Pull request closed without merging**
