### PR TITLE
remove polygon=1 (polypoints) feature

### PR DESCRIPTION
**Pull request by mtmail**
Removes the `&polygon=1` output feature.

Documentation on https://wiki.openstreetmap.org/wiki/Nominatim#Parameters says 'deprecated' since 6 August 2013‎.

### CODE REVIEW

**Comment by mtmail** [comment]
Now also returns HTTP 400 (with tests) when `polygon=1` parameter got set

**Comment by lonvia** [comment]
I think it's time to go forward with this, although I still expect quite a few complains once it gets deployed on the OSMF server. There are still quite a few requests with this parameter. Any suggestion where we could announce the change? I don't think there are many people on the mailing lists.

**Comment by mtmail** [comment]
Not really and I haven't seen other tools announce breaking changes on mailing lists either.

**Comment by lonvia** [comment]
I have now merged that as 7a94872413bbf305386322364b66bdc41c22ff4e without the check for the parameter. That means that search and reverse still work fine with the parameter, there just won't be the expected output. I suspect that a lot of consumers which still use the parameter, don't parse for the geometry anyway..

**Pull request closed without merging**
