### PR TITLE
Update DB.php

### PR DESCRIPTION
**Pull request by t-tomek**
Use SET instead of UPDATE queries to support read only databases

### CODE REVIEW

**Comment by lonvia** [comment]
UPDATE is used because it won't fail when the Postgresql version doesn't have the setting in question. To switch to SET you have to make it work for Postgresql < 11.

**Comment by mtmail** [comment]
@lonvia Are the settings needed for Postgresql < 11 ? If I recall JIT feature was added first in Postgresql 11 https://www.percona.com/blog/2018/10/18/postgresql-11-our-first-take-on-the-new-release/

**Comment by lonvia** [comment]
No, they are not. UPDATE is a noop on these versions. That's the beauty of it.

**Comment by otbutz** [comment]
Postgres 9.6 is already EOL and Postgres 10 will follow in about a week.

**Comment by lonvia** [comment]
That's not relevant.

**Comment by mtmail** [comment]
@t-tomek `DB.php` library has a method ` getPostgresVersion()` so if you move the `$this->connection =` a bit higher it should be possible to check for the version and make adjustments.
I hope postgresql < 11 get deprecated in future Nominatim versions but that'd be part of a different discussion.
The current CI tests include tests for Postgresql 9.6, 13, 14
```
                    - ubuntu: 18
                      postgresql: 9.6
                      postgis: 2.5
                      pytest: pytest
                      php: 7.2
```

**Comment by t-tomek** [comment]
@lonvia  I've just updated the patch. Now Postgres >= 11 uses SET, < 11 UPDATE statement.

**Comment by t-tomek** [comment]
I noticed that PG 9.5 support was dropped so I left SET statments (as max_parallel_workers_per_gather is supported since 9.6) but jit_above_cost is changed only if PG version is above 11

**Comment by thomas-hansen-grindr** [comment]
It seems like this change didn't make it into the 4.2.1 release available [here](https://nominatim.org/release/Nominatim-4.2.1.tar.bz2)

**Pull request merged**
