### PR TITLE
Vagrant centos8: proj52 not needed, use postgresql 11/postgis 2.5

### PR DESCRIPTION
**Pull request by mtmail**
As mentioned in https://github.com/osm-search/Nominatim/issues/1825

### CODE REVIEW

**Comment by lonvia** [comment]
Do you mind trying if it works for postgres12 + postgis3? We promote this for Ubuntu 20, so might as well use the latest version here too.

**Comment by mtmail** [comment]
Yes, that worked. I created a new PR.

**Comment by netluca1** [comment]
sorry but I remember that you were strongly advised against using postgres 12 and postgis3 (https://nominatim.org/release-docs/develop/admin/Installation/)
I quote "Postgresql 12+ and Postgis 3.0+ are known to cause performance issues. They are not recommended for a production installation at the moment."
And I remember that there was talk that just postgis3 made heavy use of postgres so as to slow everything down.
Has something changed?

**Comment by mtmail** [comment]
We think we found the performance issues, see https://github.com/osm-search/Nominatim/pull/1814 The changes are part of Nominatim 3.5. https://github.com/osm-search/Nominatim/releases

**Comment by lonvia** [comment]
Sorry, the development documentation was a bit outdated because the automatic builds were broken. I've fixed that now.

Closing this PR in favour of the other.

**Pull request closed without merging**
